modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/dudek26/Create-Blazing-Hot/issues"
license = "MIT"

[[mods]]
modId = "blazinghot"
version = "${version}"
displayName = "Create: Blazing Hot"
authors = "dudko"
description = '''
Nether- and metal-related features and QoL recipes.
'''
logoFile = "icon.png"

[[dependencies.blazinghot]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blazinghot]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blazinghot]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"