modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/dudek26/Create-Blazing-Hot/issues"
license = "MIT"

[[mods]]
modId = "blazinghot"
version = "${version}"
displayName = "Create: Blazing Hot"
authors = "dudko"
description = '''
Molten metals, casting, new Nether-related content, and QoL improvements.
'''
logoFile = "icon.png"

[[dependencies.blazinghot]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blazinghot]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blazinghot]]
modId = "create"
mandatory = true
versionRange = "[${create_version},)"
ordering = "NONE"
side = "BOTH"
