architectury {
    common(rootProject.enabled_platforms.split(","))
    platformSetupLoomIde()
}

loom {
    accessWidenerPath = file("src/main/resources/blazinghot.accesswidener")
}

repositories {
    // mavens for Create and dependencies
    maven { url = "https://jitpack.io/" } // Mixin Extras
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.neoforged.net/releases/" } // NeoForge
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

    // Compile against Create NeoForge in common
    // beware of differences across platforms!
    // dependencies must also be pulled in to minimize problems, from remapping issues to compile errors.
    // All dependencies except Flywheel and Registrate are NOT safe to use!
    // Flywheel and Registrate must also be used carefully due to differences.
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_neoforge_version}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_neoforge_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_neoforge_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_neoforge_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_neoforge_version}")

    // Needed for compiling
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
    compileOnly("net.neoforged:neoforge:${neoforge_version}")
    
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
